"""add_relationships_to_order_models

Revision ID: 2f5d5e03ffbd
Revises: e552bf48be99
Create Date: 2025-02-04 13:18:42.388729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f5d5e03ffbd'
down_revision: Union[str, None] = 'e552bf48be99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
